apiVersion: v1
kind: Secret
metadata:
  name: ai-job-search-secrets
  namespace: {{NAMESPACE}}
type: Opaque
stringData:
  GEMINI_API_KEY: "{{GEMINI_API_KEY}}"
  GIT_REPO_URL: "{{GIT_REPO_URL}}"
  GIT_TOKEN: "{{GIT_TOKEN}}"
