apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-job-search-data
  namespace: {{NAMESPACE}}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-job-search-repo
  namespace: {{NAMESPACE}}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
